brew:
    github:
        owner: muquit
        name: mailsend-go
    folder: Formula
    homepage: https://github.com/muquit/mailsend-go
    description: "Command line tool to send mail via SMTP protocol"
builds:
 - goos:
     - darwin
     - linux
     - windows
   goarch:
     - 386
     - amd64
   ignore:
     - goos: darwin
       goarch: 386
     - goos: linux
       goarch: 386
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: mac
    linux: linux
    windows: windows
  format_overrides:
    - goos: windows
      format: zip
  files:
      - docs/mailsend-go.1
      - README.md
      - LICENSE.txt
  wrap_in_directory: mailsend-go-dir
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}'
  homepage:  https://muquit.com/
  description: Command like tool to send email via SMTP protocol
  maintainer: Muhammad Muquit <muquit@muquit.com>
  license: MIT
  vendor: muquit.com
  formats:
  - deb
  - rpm
  replacements:
    amd64: linux_64-bit
    linux: linux
  bindir: /usr/local/bin
  files:
      "docs/mailsend-go.1": "/usr/local/share/man/man1/mailsend-go.1"
      "README.md": "/usr/local/share/docs/mailsend-go/README.md"
      "LICENSE.txt": "/usr/local/share/docs/mailsend-go/LICENSE.txt"

