builds:
 - goos:
     - darwin
     - linux
     - windows
   goarch:
     - amd64
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: mac
    linux: linux
    windows: windows
  format_overrides:
    - goos: windows
      format: zip
  files:
    - README.md
    - docs/*
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}'
  homepage:  https://muquit.com/
  description: Command like tool to send email via SMTP protocol
  maintainer: Muhammad Muquit <muquit@muquit.com>
  license: MIT
  vendor: muquit.com
  formats:
  - deb
  - rpm

